export declare const rot: (arr: number[][], derect: boolean) => any[];
export declare const rot90: (arr: number[][], time?: number) => any[];
export declare class Cube {
    start_time: number;
    last_step: string[];
    face: number[][];
    back: number[][];
    right: number[][];
    left: number[][];
    up: number[][];
    down: number[][];
    color: any;
    constructor();
    reset(this: any): void;
    get_jiao(this: any): void;
    get_colour(this: any): void;
    get_leng(this: any): void;
    F(): void;
    F_(): void;
    B(): void;
    B_(): void;
    L(): void;
    L_(): void;
    R(): void;
    R_(): void;
    U(): void;
    U_(): void;
    D(): void;
    D_(): void;
    check(): boolean;
    re_do(msg: string): boolean;
}
